// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krgsjtthbtypcvezzykz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZ3NqdHRoYnR5cGN2ZXp6eWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDgyODUsImV4cCI6MjA2NTgyNDI4NX0.9shMGqmnLdlNFSeIPDouDXE-WBwunKd7EELPBtAbuW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);